### ISSUE TITLE
Error Displaying Assignments

### ISSUE THREAD

**Issue by gnaneswar-k** [IIITH-Resources/Computer_Programming#5]
Opening the assignment PDFs on mobile shows the 404 Error page.

1. Go to Assignments Page of CPro
2. Click on any of the PDFs
3. See error

![Screenshot_20220205-165109](https://user-images.githubusercontent.com/97674245/152639964-80241b25-6a74-41e4-a8cf-61661840d737.png)

 - Device: motorola edge 20 pro
 - OS: Android 11
 - Browser: Google Chrome
 - Version 97.0.4692.98

Last time I checked in my Laptop I think think it's fine, so seems like a mobile only issue.

**Comment by b-beri** [comment]
Kindly check once again. Yeah Ig there's some problem.

**Comment by b-beri** [comment]
Thanks for Reporting the issue.

**Comment by ghost** [comment]
I can't reproduce the issue. Did you fix it already ?

**Comment by bhavberi** [comment]
@gnaneswar-k Is the issue resolved ?

**Comment by gnaneswar-k** [comment]
Yes it's resolved, I'll close it with this comment then.
