### ISSUE TITLE
String sort code

### ISSUE THREAD

**Issue by gnaneswar-k** [IIITH-Resources/Computer_Programming#7]
Lots of people usually ask for the string sort code which sir shared, so maybe we could add that in here for easy access.

**Comment by gnaneswar-k** [comment]
I'll also ask around if anyone prefers any other important code which sir shared to also be present

**Comment by bhavberi** [comment]
Yeah I have already asked @MaharnavS to add, but he's too lazy to write it from the Video

**Comment by bhavberi** [comment]
@gnaneswar-k Can you add most of the codes that sir have discussed, as most of them are important (mainly last few days).
Also, send your codes to @MaharnavS for formatting.

**Comment by gnaneswar-k** [comment]
Oh then sir didn't share it? I thought he sent it as a mail, that's why I suggested

**Comment by gnaneswar-k** [comment]
Okay I'll try, but I didn't actually type them in my system. I'm anyways going to see the recent lectures  for revision, so I'll type that time and sent it to Maharnav. But can't guarantee it'll be done before the Quiz

**Comment by ghost** [comment]
Bro, that's the thing. Sir didn't send it and I don't pay attention in class. Either someone send me the code or maybe motivate me to write it after quiz

**Comment by b-beri** [comment]
I think it's done now.
